[buildPlans.iosevka-storm]
family = "Iosevka Storm"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-storm.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-interrupted-unilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-j = "serifed"
capital-k = "curly-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "curly-motion-serifed"
capital-s = "unilateral-serifed"
capital-t = "serifless"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-tailed"
b = "toothless-corner-motion-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
e = "rounded"
f = "tailed-crossbar-at-x-height"
g = "single-storey-flat-hook-serifed"
h = "straight-motion-serifed"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-serifed"
l = "tailed-serifed"
m = "short-leg-tailed"
n = "tailed-motion-serifed"
p = "motion-serifed"
q = "diagonal-tailed-motion-serifed"
r = "compact-base-serifed"
s = "unilateral-serifed"
t = "standard-short-neck"
u = "motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-motion-serifed"
y = "straight-motion-serifed"
z = "straight-top-serifed"
long-s = "flat-hook-tailed"
eszet = "sulzbacher"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
capital-gamma = "top-right-serifed"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight-turn"
lower-mu = "tailed"
lower-xi = "flat-top"
zero = "slashed"
two = "curly-neck"
three = "two-arcs"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-serifless"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "dots"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
question = "smooth"
punctuation-dot = "round"
lig-neq = "slightly-slanted"
